export const ACTION_TYPE = {
  SET_USER: 'SET_USER',
  LOGOUT: 'LOGOUT',
  SET_POST_DATA: 'SET_POST_DATA',
  SET_COMMENT_DATA: 'SET_COMMENT_DATA',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  RESET_POST_DATA: 'RESET_POST_DATA',
  SET_SEARCH_PHRASE: 'SET_SEARCH_PHRASE',
  SET_SEARCH_RESULTS_COUNT: 'SET_SEARCH_RESULTS_COUNT',
  SET_USER_INITIALIZED: 'SET_USER_INITIALIZED',
  ADD_COMMENT: 'ADD_COMMENT',
  REMOVE_COMMENT: 'REMOVE_COMMENT',
};
