export const ACTION_TYPE = {
  SET_USER: 'SET_USER',
  LOGOUT: 'LOGOUT',


  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  INCREASE_CART_QUANTITY: 'INCREASE_CART_QUANTITY',
  DECREASE_CART_QUANTITY: 'DECREASE_CART_QUANTITY',
  CLEAR_CART: 'CLEAR_CART',
};
